apiVersion: v1
kind: Service
metadata:
  name: api-ingress
spec:
  type: NodePort
  selector:
      app: api
  ports:
  - port: 8080
    targetPort: 8080
    name: api
  - port: 5005
    targetPort: 5005
    nodePort: 30000
    name: debugger
